### ISSUE TITLE
trip_id is written to trips.txt instead of route_id

### ISSUE THREAD

**Issue by highsource** [patrickbr/db-api-to-gtfs#4]
This:

```
                trip_writer.writerow({
                    'route_id': tid,
                    'service_id': trip['service_id'],
                    'trip_id': tid,
                    'trip_headsign': trip['headsign']
                })
```

Should be actually this:

```
                trip_writer.writerow({
                    'route_id': trip['route_id'],
                    'service_id': trip['service_id'],
                    'trip_id': tid,
                    'trip_headsign': trip['headsign']
                })
```

I.e. `route_id` should be `trip['route_id']`, not `tid`.

**Comment by patrickbr** [comment]
Thanks for spotting that typo, you are absolutely right.

**Comment by highsource** [comment]
Is probably already fixed via merge.

**Comment by patrickbr** [comment]
Yes, fixed with 58144bae6d02387f9e2b96c3cd5e470586eae28d

**Comment by highsource** [comment]
Great, thanks. :+1:
Nice to work with you.

**Comment by gerbsen** [comment]
Hey, I just stumbled over this issue, since it is still present in the demo download file available at: http://patrickbrosi.de/de/projects/dbgtfs/. Is there a new file somewhere or should I generate it myself?

**Comment by highsource** [comment]
@gerbsen I have never told you about https://github.com/fredlockheed/db-fv-gtfs.

**Comment by gerbsen** [comment]
AWESOME! FYI.. Im currently trying to import this data into our [germany endpoint](https://apps.route360.net/demo/#/map?areaID=germany&travelTime=30&travelTimeRangeID=0&travelType=transit&colorRangeID=0&sources=52.516221,13.386154&intersection=union&transition=true&mapstyle=mi.0ad4304c)! :) Can't wait to see travel time polygons for ICE's :D

**Comment by gerbsen** [comment]
Thank you for sharing!

**Comment by highsource** [comment]
@gerbsen Ah, you're from Route360. :) Great, I'd love to see isochrones for ICEs, too. Please drop [me](http://xing.to/va) a line when you've got it.

Many thanks to @fredlockheed for the feed.

**Comment by patrickbr** [comment]
I have updated the feed published on http://patrickbrosi.de/de/projects/dbgtfs/. @fredlockheed's 2016 feed is now also mentioned there!

**Comment by gerbsen** [comment]
@highsource I've waited years for this: https://apps.route360.net/demo/#/map?areaID=germany&travelTime=120&travelTimeRangeID=2&travelType=transit&colorRangeID=0&sources=51.344741,12.380776&intersection=union&transition=true&mapstyle=mi.0ad4304c

**Comment by highsource** [comment]
@gerbsen Wow very cool. :)

**Comment by highsource** [comment]
Many thanks to @patrickbr and @fredlockheed!
